org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -Dkotlin.daemon.jvm.options="-Xmx3g" -XX:+HeapDumpOnOutOfMemoryError
org.gradle.configuration-cache.parallel=true

kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

# Custom

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app"s APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
android.builtInKotlin=false
android.newDsl=false

# Maven Central Publication placeholders (Override in ~/.gradle/gradle.properties)
# Generate token at https://central.sonatype.com -> Account -> User Token
# mavenCentralUsername=YOUR_TOKEN_USERNAME
# mavenCentralPassword=YOUR_TOKEN_PASSWORD
# signingInMemoryKey=YOUR_GPG_SECRET_KEY
# signingInMemoryKeyPassword=YOUR_GPG_PASSWORD