package org.graphiks.kffi.wayland

const val WL_MARSHAL_FLAG_DESTROY: Int = 1
const val ZWLR_SCREENCOPY_FRAME_FLAGS_Y_INVERT: Int = SCREENCOPY_FRAME_FLAGS_Y_INVERT
const val ZWP_POINTER_CONSTRAINTS_V1_LIFETIME_ONESHOT: Int = POINTER_CONSTRAINTS_LIFETIME_ONESHOT
const val ZWP_POINTER_CONSTRAINTS_V1_LIFETIME_PERSISTENT: Int = POINTER_CONSTRAINTS_LIFETIME_PERSISTENT
