package org.graphiks.kffi.engine.upcallfixture

import java.util.concurrent.CopyOnWriteArrayList

/**
 * Test upcall dispatcher in a package distinct from [JvmUpcallEngine].
 *
 * The object is private (a package-private class at the JVM level), so the
 * engine can access it across packages only through privateLookupIn. Switching
 * back to `MethodHandles.lookup().findStatic` would make the test fail with
 * IllegalAccessException. This is the shape generated by kextract: a `private
 * object` with a static dispatch method.
 *
 * [TestUpcallDispatchersBridge] exposes the dispatcher class and capture queue
 * to the test without changing the object's JVM visibility.
 */
private object TestUpcallDispatchers {
    val captured: MutableList<Triple<Int, Int, Long>> = CopyOnWriteArrayList()

    @JvmStatic
    fun captureStatusValueUserdata(status: Int, value: Int, userdata: Long) {
        captured += Triple(status, value, userdata)
    }

    @JvmStatic
    fun captureReturningInt(status: Int, userdata: Long): Int {
        captured += Triple(status, -1, userdata)
        return status + 1
    }
}

object TestUpcallDispatchersBridge {
    val dispatcherClass: Class<*> = TestUpcallDispatchers::class.java

    val captured: MutableList<Triple<Int, Int, Long>>
        get() = TestUpcallDispatchers.captured
}
