package org.graphiks.kffi.x11.generated

typealias XImage = KffiXImageStorage
typealias XWindowAttributes = KffiXWindowAttributesStorage
typealias XClientMessageEvent = KffiXClientMessageEventStorage
typealias XSelectionEvent = KffiXSelectionEventStorage
typealias XSetWindowAttributes = KffiXSetWindowAttributesStorage
