#!/usr/bin/env python3
"""Regenerate the project-owned variable test font for kffi-harfbuzz.

The fixture is a minimal OpenType variable font built entirely from this
script with fontTools. It contains:

* a single ``wght`` axis (100 / 400 / 900, default 400) declared in ``fvar``;
* a ``gvar`` glyph plus ``HVAR`` so the horizontal advance of ``A`` varies with
  the axis (500 / 600 / 800 design units);
* ``vhea`` and ``vmtx`` so ``hb_font_get_glyph_v_advance`` returns a
  non-trivial value (1300 design units at the default scale).

No third-party font data is used. The output is byte-for-byte reproducible:
run this script and the SHA-256 is stable.

Usage:

    python3 generate_kffi_var_font.py <output-directory>

The script writes ``KffiVar.ttf`` into the directory, which is expected to be
``kffi-harfbuzz/src/jvmTest/resources/fonts/kffi-var``.
"""

from __future__ import annotations

import os
import sys

from fontTools import varLib
from fontTools.designspaceLib import AxisDescriptor, DesignSpaceDocument, SourceDescriptor
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

UPEM = 1000
GLYPHS = [".notdef", "space", "A"]
WEIGHTS = (100, 400, 900)
# Design-unit horizontal advance of "A" per weight; 400 is the default instance.
ADVANCE_A = {100: 500, 400: 600, 900: 800}
# Constant vertical advance of "A": the vertical axis does not vary.
ADVANCE_V_A = 1300
# Fixed timestamps keep the generated bytes reproducible.
TIMESTAMP = 0x7C259DC0


def draw_a(pen: TTGlyphPen, advance: int) -> None:
    """Draws a simple triangle whose width tracks the horizontal advance."""
    pen.moveTo((100, 0))
    pen.lineTo((advance - 100, 0))
    pen.lineTo((advance // 2, 700))
    pen.closePath()


def build_master(path: str, weight: int) -> None:
    """Writes one static master at [weight]."""
    advance = ADVANCE_A[weight]
    builder = FontBuilder(UPEM, isTTF=True)
    builder.setupGlyphOrder(GLYPHS)
    builder.setupCharacterMap({0x20: "space", 0x41: "A"})

    glyphs = {}
    for name in GLYPHS:
        pen = TTGlyphPen(None)
        if name == "A":
            draw_a(pen, advance)
        glyphs[name] = pen.glyph()
    builder.setupGlyf(glyphs)

    builder.setupHorizontalMetrics({".notdef": (600, 0), "space": (250, 0), "A": (advance, 100)})
    builder.setupVerticalMetrics(
        {".notdef": (1000, 0), "space": (1000, 0), "A": (ADVANCE_V_A, 100)}
    )
    builder.setupHorizontalHeader(ascent=800, descent=-200)
    builder.setupVerticalHeader(ascent=500, descent=-500)
    builder.setupNameTable({"familyName": "KffiVar", "styleName": "Regular"})
    builder.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800, usWinDescent=200)
    builder.setupPost()
    builder.setupMaxp()
    builder.setupHead(unitsPerEm=UPEM)
    builder.save(path)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    output_dir = os.path.abspath(sys.argv[1])
    os.makedirs(output_dir, exist_ok=True)

    for weight in WEIGHTS:
        build_master(os.path.join(output_dir, f"master_{weight}.ttf"), weight)

    designspace = DesignSpaceDocument()
    axis = AxisDescriptor()
    axis.name = "Weight"
    axis.tag = "wght"
    axis.minimum = 100
    axis.default = 400
    axis.maximum = 900
    designspace.addAxis(axis)
    for weight in WEIGHTS:
        source = SourceDescriptor()
        source.filename = f"master_{weight}.ttf"
        source.path = os.path.join(output_dir, source.filename)
        source.location = {"Weight": weight}
        designspace.addSource(source)

    variable_font, _, _ = varLib.build(designspace)

    # Freeze the head timestamps so the output is reproducible.
    variable_font.recalcTimestamp = False
    variable_font["head"].created = TIMESTAMP
    variable_font["head"].modified = TIMESTAMP

    variable_font.save(os.path.join(output_dir, "KffiVar.ttf"))

    # The intermediate masters are build inputs, not fixtures.
    for weight in WEIGHTS:
        os.remove(os.path.join(output_dir, f"master_{weight}.ttf"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
