import java.security.MessageDigest
import java.util.Base64
import org.gradle.api.publish.maven.MavenPublication

plugins {
    `kotlin-multiplatform`
    id("com.android.kotlin.multiplatform.library")
    id("ygdrasil.conventions.kmp-publish")
}

// The sibling native module is evaluated *after* :kffi-harfbuzz, so its `extra[...]`
// properties are not readable here at configuration time. Its build directory is
// available pre-evaluation, so the staged archive paths are derived from it directly.
val iosNativeBuildDirectory = project(":kffi-harfbuzz-ios-native").layout.buildDirectory

// ---------------------------------------------------------------------------
// Build-time artifact identity.
//
// The identity's artifactSha256 must describe the archive that is actually
// linked into each iOS slice. A digest is toolchain- and build-path-dependent,
// so it is computed from the sealed archive at build time and emitted as a
// generated Kotlin `actual` for the matching target. Declaring the staged
// archive as the task input keeps the reported identity in lockstep with the
// embedded archive: change the archive and the generated digest (and therefore
// the binding identity) is rewritten before the target compiles.
// ---------------------------------------------------------------------------
val iosDigestTasks = listOf(
    Triple("Device", "iphoneos", "iosArm64"),
    Triple("Simulator", "iphonesimulator", "iosSimulatorArm64"),
).associate { (suffix, sdk, targetName) ->
    val archive = iosNativeBuildDirectory.file("harfbuzz/$sdk/lib/libharfbuzz.a")
    val generatedDirectory = layout.buildDirectory.dir("generated/harfbuzzIosDigest$suffix")
    val artifactId = "org.graphiks:kffi-harfbuzz-${targetName.lowercase()}:$version:$targetName/libharfbuzz.a"
    val generator = tasks.register("generateHarfBuzzIosDigest$suffix") {
        group = "harfbuzz"
        description = "Generates the HarfBuzz binding identity constants for iOS $sdk."
        val archiveFile = archive.get().asFile
        inputs.file(archiveFile)
        outputs.dir(generatedDirectory)
        // Sealing this slice's archive is the producer of the `.a` digest. Depend on the
        // per-slice seal task rather than the `buildHarfBuzzIos` aggregate, so generating the
        // device digest does not build the simulator slice (and vice versa).
        // String task path: no cross-project evaluation at configuration time.
        dependsOn(":kffi-harfbuzz-ios-native:sealHarfBuzzIos$suffix")
        doLast {
            val digest = MessageDigest.getInstance("SHA-256")
                .digest(archiveFile.readBytes())
                .joinToString(separator = "") { byte -> "%02x".format(byte) }
            val source = generatedDirectory.get().file("IosHarfBuzzArtifactDigests.kt").asFile
            source.parentFile.mkdirs()
            source.writeText(
                buildString {
                    appendLine("// Generated by :kffi-harfbuzz:generateHarfBuzzIosDigest$suffix. Do not edit.")
                    appendLine("package org.graphiks.kffi.harfbuzz")
                    appendLine()
                    appendLine("internal actual val iosHarfBuzzArtifactId: String = \"$artifactId\"")
                    appendLine()
                    appendLine("internal actual val iosHarfBuzzArtifactSha256: String = \"$digest\"")
                    appendLine()
                    appendLine("internal actual val iosHarfBuzzIosSdkName: String = \"$sdk\"")
                },
            )
        }
    }
    targetName to (generator to generatedDirectory)
}

// ---------------------------------------------------------------------------
// iOS shaping fixture.
//
// Kotlin/Native has no classpath-resource mechanism, so the audited DejaVu Sans
// fixture used by the JVM and Android tests is embedded into the iOS test
// source set as a generated Kotlin source. The task reads the same checked-in
// TTF and emits a Base64 literal (chunked to stay under the class-file UTF-8
// constant limit); declaring the TTF as the task input keeps the embedded bytes
// in lockstep with the fixture, so the test can never shape a stale font.
// ---------------------------------------------------------------------------
val iosFontFixtureSource = layout.projectDirectory.file("src/jvmTest/resources/fonts/dejavu/DejaVuSans.ttf")
val iosFontFixtureDirectory = layout.buildDirectory.dir("generated/harfbuzzIosFontFixture")
val generateHarfBuzzIosFontFixture = tasks.register("generateHarfBuzzIosFontFixture") {
    group = "harfbuzz"
    description = "Generates the embedded DejaVu Sans fixture for the iOS test source set."
    val fixtureFile = iosFontFixtureSource.asFile
    inputs.file(fixtureFile)
    outputs.dir(iosFontFixtureDirectory)
    doLast {
        val base64 = Base64.getEncoder().encodeToString(fixtureFile.readBytes())
        // A JVM/class-file string constant is capped at 65535 UTF-8 bytes, so the
        // Base64 payload is emitted as concatenated 8 KiB chunks.
        val chunkSize = 8 * 1024
        val source = iosFontFixtureDirectory.get().file("IosHarfBuzzFontFixture.kt").asFile
        source.parentFile.mkdirs()
        source.writeText(
            buildString {
                appendLine("@file:OptIn(ExperimentalEncodingApi::class)")
                appendLine()
                appendLine("package org.graphiks.kffi.harfbuzz")
                appendLine()
                appendLine("import kotlin.io.encoding.Base64")
                appendLine("import kotlin.io.encoding.ExperimentalEncodingApi")
                appendLine()
                appendLine("// Generated by :kffi-harfbuzz:generateHarfBuzzIosFontFixture from")
                appendLine("// src/jvmTest/resources/fonts/dejavu/DejaVuSans.ttf. Do not edit.")
                appendLine()
                appendLine("/** The audited DejaVu Sans shaping fixture, embedded for Kotlin/Native. */")
                appendLine("internal val dejaVuSansTtf: ByteArray = Base64.Mime.decode(")
                appendLine("    buildString(${base64.length}) {")
                base64.chunked(chunkSize).forEach { chunk -> appendLine("        append(\"$chunk\")") }
                appendLine("    },")
                appendLine(")")
            },
        )
    }
}

// ---------------------------------------------------------------------------
// Licence notices for the published iOS artifacts.
//
// The iOS klibs embed the pinned static `libharfbuzz.a`, whose "Old MIT"
// licence requires the copyright notice to accompany binary distributions. The
// notice and the licence text live in the (unpublished) native module; both are
// attached as classified artifacts to the root and both iOS publications so a
// consumer of `org.graphiks:kffi-harfbuzz-iosarm64` / `-iossimulatorarm64`
// (and the root coordinate) receives them beside the klib.
// ---------------------------------------------------------------------------
val harfBuzzNoticeFile = rootProject.layout.projectDirectory
    .file("kffi-harfbuzz-ios-native/NOTICE.md").asFile
val harfBuzzLicenseFile = rootProject.layout.projectDirectory
    .file("kffi-harfbuzz-ios-native/licenses/HARFBUZZ-OLD-MIT.txt").asFile

publishing {
    publications.withType<MavenPublication>().configureEach {
        if (name == "kotlinMultiplatform" || name.startsWith("ios")) {
            artifact(harfBuzzNoticeFile) {
                classifier = "NOTICE"
                extension = "md"
            }
            artifact(harfBuzzLicenseFile) {
                classifier = "HARFBUZZ-OLD-MIT"
                extension = "txt"
            }
        }
    }
}

kotlin {
    jvmToolchain(25)
    explicitApi()

    // Both the JVM and Android actual classes are declared as expect/actual classes.
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_25)
        }
    }

    android {
        namespace = "org.graphiks.kffi.harfbuzz"
        compileSdk = 36
        minSdk = 28
        packaging {
            jniLibs {
                useLegacyPackaging = true
            }
        }
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
        withDeviceTest {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }
    }

    val iosArm64Target = iosArm64()
    val iosSimulatorArm64Target = iosSimulatorArm64()

    // -----------------------------------------------------------------------
    // Static HarfBuzz cinterop for iOS.
    //
    // The archive (libharfbuzz.a) and public headers are produced by the sibling
    // :kffi-harfbuzz-ios-native module. That module is included *after*
    // :kffi-harfbuzz in settings.gradle.kts, so it is not guaranteed to be
    // evaluated when this script is configured: reading its `extra[...]`
    // properties here would resolve to null. Instead we derive the well-known
    // paths from its build directory (available pre-evaluation) and depend on
    // the producing aggregate task by task path (also evaluation-order safe).
    //
    // The cinterop static-library search path is passed via `-libraryPath`;
    // the archive name itself is declared in the .def as `staticLibraries`.
    // -----------------------------------------------------------------------
    listOf(
        iosArm64Target to "iphoneos",
        iosSimulatorArm64Target to "iphonesimulator",
    ).forEach { (target, sdk) ->
        val includeDirectory = iosNativeBuildDirectory.dir("harfbuzz/$sdk/include/harfbuzz").get().asFile
        val libraryDirectory = iosNativeBuildDirectory.dir("harfbuzz/$sdk/lib").get().asFile
        val interop = target.compilations.getByName("main").cinterops.create("harfbuzz") {
            defFile(project.file("src/nativeInterop/cinterop/harfbuzz.def"))
            // The umbrella header lives beside the .def; the pinned HarfBuzz
            // headers (hb.h, hb-ot.h) live in the staged include directory.
            includeDirs(project.file("src/nativeInterop/cinterop"), includeDirectory)
            extraOpts("-libraryPath", libraryDirectory.absolutePath)
        }
        tasks.named(interop.interopProcessingTaskName) {
            // String task path: no cross-project project()/tasks.named() at
            // configuration time, so this cannot race module evaluation.
            dependsOn(":kffi-harfbuzz-ios-native:buildHarfBuzzIos")
        }
    }

    sourceSets {
        jvmMain.dependencies {
            implementation(project(":kffi"))
        }
        jvmTest.dependencies {
            implementation(kotlin("test"))
        }

        val androidMain by getting {
            dependencies {
                implementation(project(":kffi"))
                implementation(project(":kffi-harfbuzz-android-native"))
            }
        }

        iosMain.dependencies {
            implementation(project(":kffi"))
        }

        val androidDeviceTest by getting {
            dependencies {
                implementation(libs.androidx.test.ext.junit)
                implementation(libs.androidx.test.runner)
                implementation(kotlin("test"))
            }
        }

        // Wire the generated identity constants into each iOS slice.
        val iosArm64Main by getting {
            kotlin.srcDir(iosDigestTasks.getValue("iosArm64").second)
        }
        val iosSimulatorArm64Main by getting {
            kotlin.srcDir(iosDigestTasks.getValue("iosSimulatorArm64").second)
        }
        val iosSimulatorArm64Test by getting {
            kotlin.srcDir(iosFontFixtureDirectory)
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

// Make each iOS compilation depend on the digest generator for its slice, so the reported
// identity is always produced from the archive that compilation links.
tasks.named("compileKotlinIosArm64") { dependsOn(iosDigestTasks.getValue("iosArm64").first) }
tasks.named("compileKotlinIosSimulatorArm64") { dependsOn(iosDigestTasks.getValue("iosSimulatorArm64").first) }
tasks.named("compileTestKotlinIosSimulatorArm64") { dependsOn(generateHarfBuzzIosFontFixture) }

// The generated identity constants live in the iOS main source set, so the per-slice sources
// jars (built by the publication) consume the generator's output and must depend on it too.
tasks.matching { it.name == "iosArm64SourcesJar" }
    .configureEach { dependsOn(iosDigestTasks.getValue("iosArm64").first) }
tasks.matching { it.name == "iosSimulatorArm64SourcesJar" }
    .configureEach { dependsOn(iosDigestTasks.getValue("iosSimulatorArm64").first) }

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    jvmArgs("--enable-native-access=ALL-UNNAMED")
    onlyIf("HarfBuzz supports Linux, macOS and Windows") {
        val os = System.getProperty("os.name")
        os.startsWith("Mac") || os.startsWith("Linux") || os.startsWith("Windows")
    }
}
