package org.graphiks.kffi.engine

import org.graphiks.kffi.NativeAddress
import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.Linker
import java.lang.foreign.MemoryLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandles

/**
 * JVM upcall engine: factory for trampolines by signature shape.
 *
 * Symmetric with UpcallEngine (Android). Generated code (kextract) provides
 * the dispatcher class and static method with its encoded signature; the engine
 * builds the corresponding FFM stub. The engine does not route callbacks: token
 * routing remains in the generated dispatcher through
 * CallbackRuntime.dispatchSafely, with userdata in its actual C position (last
 * parameter for wgpu).
 *
 * dispatchSig encoding uses the Java convention: I=int, J=long, F=float,
 * D=double, Z=boolean, and V=void. Pointers are encoded as J (a 64-bit long
 * carrier, ABI-identical across supported platforms, as the Android C engine
 * uses jlong). A V return produces an ofVoid descriptor.
 *
 * Dispatch-method resolution uses privateLookupIn, accepting private trampoline
 * objects generated by kextract, like Android's GetStaticMethodID
 * (kffi_upcall.c), which bypasses Java access checks. It requires the classpath
 * (unnamed modules and open packages); if kffi or a consumer moves to the
 * module path (a named module), access throws IllegalAccessException.
 *
 * Native-access note: the generic [allocateTrampoline] encoding cannot express
 * structs by value, I8/I16/CHAR16 scalars, or multiple indirections. The finite
 * Objective-C struct shapes below use closed descriptors; generated callbacks
 * outside those shapes are emitted by kextract through a direct FFM fallback
 * (`KotlinCallbackJvmEmitter.emitFfmTrampoline`) that calls
 * `Linker.upcallStub`/`MethodHandles.lookup()` in generated code. This path
 * requires `--enable-native-access=ALL-UNNAMED` at launch; otherwise the JVM
 * warns and will block the call in a future JDK release.
 */
object JvmUpcallEngine {

    private val linker = Linker.nativeLinker()
    private val arena = Arena.global()

    /**
     * Creates a trampoline that calls [dispatcherClass]'s static
     * [dispatchMethod] with signature [dispatchSig] (for example, "(IIJ)V").
     * Stub parameters follow C order: the first receives the first C argument
     * and the last receives userdata/token when the callback is routed.
     */
    fun allocateTrampoline(
        dispatcherClass: Class<*>,
        dispatchMethod: String,
        dispatchSig: String,
    ): NativeAddress {
        val (returnType, parameterTypes) = parseSig(dispatchSig)
        val descriptor = if (returnType == null) {
            FunctionDescriptor.ofVoid(*parameterTypes.map { it.layout }.toTypedArray())
        } else {
            FunctionDescriptor.of(returnType.layout, *parameterTypes.map { it.layout }.toTypedArray())
        }
        return allocateTrampoline(dispatcherClass, dispatchMethod, descriptor)
    }

    fun allocateObjCVoidObjectRangeTrampoline(
        dispatcherClass: Class<*>,
        dispatchMethod: String,
    ): NativeAddress = allocateTrampoline(
        dispatcherClass,
        dispatchMethod,
        FunctionDescriptor.ofVoid(pointer, pointer, pointer, objcRange),
    )

    fun allocateObjCVoidObjectRangeRangeTrampoline(
        dispatcherClass: Class<*>,
        dispatchMethod: String,
    ): NativeAddress = allocateTrampoline(
        dispatcherClass,
        dispatchMethod,
        FunctionDescriptor.ofVoid(pointer, pointer, pointer, objcRange, objcRange),
    )

    fun allocateObjCRangeTrampoline(
        dispatcherClass: Class<*>,
        dispatchMethod: String,
    ): NativeAddress = allocateTrampoline(
        dispatcherClass,
        dispatchMethod,
        FunctionDescriptor.of(objcRange, pointer, pointer),
    )

    fun allocateObjCObjectRangeOutRangeTrampoline(
        dispatcherClass: Class<*>,
        dispatchMethod: String,
    ): NativeAddress = allocateTrampoline(
        dispatcherClass,
        dispatchMethod,
        FunctionDescriptor.of(pointer, pointer, pointer, objcRange, pointer),
    )

    fun allocateObjCRectRangeOutRangeTrampoline(
        dispatcherClass: Class<*>,
        dispatchMethod: String,
    ): NativeAddress = allocateTrampoline(
        dispatcherClass,
        dispatchMethod,
        FunctionDescriptor.of(objcRect, pointer, pointer, objcRange, pointer),
    )

    fun allocateObjCULongPointTrampoline(
        dispatcherClass: Class<*>,
        dispatchMethod: String,
    ): NativeAddress = allocateTrampoline(
        dispatcherClass,
        dispatchMethod,
        FunctionDescriptor.of(ValueLayout.JAVA_LONG, pointer, pointer, objcPoint),
    )

    private fun allocateTrampoline(
        dispatcherClass: Class<*>,
        dispatchMethod: String,
        descriptor: FunctionDescriptor,
    ): NativeAddress {
        val methodHandle = MethodHandles.privateLookupIn(dispatcherClass, MethodHandles.lookup())
            .findStatic(dispatcherClass, dispatchMethod, descriptor.toMethodType())
        return NativeAddress(linker.upcallStub(methodHandle, descriptor, arena).address())
    }

    private val pointer = ValueLayout.JAVA_LONG

    private val objcRange = MemoryLayout.structLayout(
        ValueLayout.JAVA_LONG,
        ValueLayout.JAVA_LONG,
    )

    private val objcPoint = MemoryLayout.structLayout(
        ValueLayout.JAVA_DOUBLE,
        ValueLayout.JAVA_DOUBLE,
    )

    private val objcRect = MemoryLayout.structLayout(objcPoint, objcPoint)

    private enum class Carrier(val layout: ValueLayout) {
        I(ValueLayout.JAVA_INT),
        J(ValueLayout.JAVA_LONG),
        F(ValueLayout.JAVA_FLOAT),
        D(ValueLayout.JAVA_DOUBLE),
        Z(ValueLayout.JAVA_BOOLEAN),
    }

    /** "(IIJ)V" -> null return (void) and [I, I, J] parameters. */
    private fun parseSig(sig: String): Pair<Carrier?, List<Carrier>> {
        val parameters = sig.substringAfter('(').substringBefore(')')
            .map { Carrier.valueOf(it.toString()) }
        val returnPart = sig.substringAfter(')')
        return (if (returnPart == "V") null else Carrier.valueOf(returnPart)) to parameters
    }
}
